apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-bun-ts
  namespace: default
  annotations:
    networking.knative.dev/ingress.class: kourier.ingress.networking.knative.dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          env:
            - name: OTEL_SERVICE_NAME
              value: hello-bun-ts
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /healthz
