apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CONFIG_MAP}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: workerd
    app.kubernetes.io/instance: ${NAME}
data:
  config.capnp: |
    using Workerd = import "/workerd/workerd.capnp";

    const config :Workerd.Config = (
      services = [
        (name = "main", worker = .mainWorker),
      ],

      sockets = [
        (
          name = "http",
          address = "*:8080",
          http = (),
          service = "main"
        ),
      ]
    );

    const mainWorker :Workerd.Worker = (
      serviceWorkerScript = embed "worker.js",
      compatibilityDate = "2025-06-01",
    );
  worker.js: |
    addEventListener("fetch", event => {
      const url = new URL(event.request.url);
      const body = JSON.stringify({
        service: "workerd",
        path: url.pathname,
        message: "Hello from workerd on Kubernetes",
      });

      event.respondWith(new Response(body, {
        headers: {
          "content-type": "application/json; charset=utf-8",
        },
      }));
    });
