replicaCount: 1

crds:
  create: true

config:
  create: true
  clusterWide: true

monitoring:
  podMonitorEnabled: false
  grafanaDashboard:
    create: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
