apiVersion: v1
kind: Secret
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: neki-rustfs-credentials
type: Opaque
stringData:
  access-key: "${RUSTFS_ACCESS_KEY}"
  secret-key: "${RUSTFS_SECRET_KEY}"
