apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: neki-worker-node
    app.kubernetes.io/instance: ${NAME}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: neki-worker-node
    app.kubernetes.io/instance: ${NAME}
  ports:
    - name: http
      port: 80
      targetPort: http
