apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-bun-ts
  namespace: ${NAMESPACE}
  annotations:
    networking.knative.dev/ingress.class: kourier.ingress.networking.knative.dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        dapr.io/app-id: hello-bun-ts
        dapr.io/app-port: "3000"
        dapr.io/config: hello-bun-ts-config
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "9091"
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          env:
            - name: OTEL_SERVICE_NAME
              value: hello-bun-ts
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: DAPR_SECRET_STORE
              value: vault
            - name: DAPR_SECRET_NAME
              value: hello-bun-ts
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /healthz
