apiVersion: v1
kind: ServiceAccount
metadata:
  name: neki-vso
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: neki-vault
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: neki-vault-auth
spec:
  vaultConnectionRef: neki-vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: neki-app
    serviceAccount: neki-vso
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: neki-example
spec:
  type: kv-v2
  mount: secret
  path: neki/example
  refreshAfter: 30s
  vaultAuthRef: neki-vault-auth
  destination:
    create: true
    name: neki-example
    type: Opaque

