apiVersion: v1
kind: Secret
metadata:
  name: bucket-credentials
  namespace: neon
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://rustfs-svc.rustfs.svc.cluster.local:9000
  BUCKET_NAME: neon
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-controller-database
  namespace: neon
type: Opaque
stringData:
  uri: postgresql://app:replace-me@postgres-cluster-rw.postgres.svc.cluster.local:5432/app
