apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  labels:
    app.kubernetes.io/part-of: neki
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
