prometheusOperator:
  admissionWebhooks:
    enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    probeSelector: {}
    probeNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

grafana:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
