replicaCount: 1

crds:
  enabled: true

image:
  repository: docker.io/redpandadata/redpanda-operator

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

monitoring:
  enabled: false
