replicaCount: 1

mode:
  standalone:
    enabled: true
  distributed:
    enabled: false

ingress:
  enabled: false

service:
  type: ClusterIP
  endpoint:
    port: 9000
  console:
    port: 9001

config:
  rustfs:
    region: us-east-1
    console_enable: "true"
    console_address: ":9001"
    obs_log_directory: ""

storageclass:
  name: ""
  dataStorageSize: 10Gi
  logStorageSize: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

affinity:
  podAntiAffinity:
    enabled: false
  nodeAffinity: {}
